/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppShellRouteImport } from './routes/_app._shell'
import { Route as AppWorkoutRouteImport } from './routes/_app.workout'
import { Route as AppShellIndexRouteImport } from './routes/_app._shell.index'
import { Route as AppShellExercisesRouteImport } from './routes/_app._shell.exercises'
import { Route as AppShellHistoryRouteImport } from './routes/_app._shell.history'
import { Route as AppShellProgressRouteImport } from './routes/_app._shell.progress'
import { Route as AppShellRoutinesRouteImport } from './routes/_app._shell.routines'
import { Route as AppShellSettingsRouteImport } from './routes/_app._shell.settings'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppShellRoute = AppShellRouteImport.update({
  id: '/_shell',
  getParentRoute: () => AppRoute,
} as any)
const AppWorkoutRoute = AppWorkoutRouteImport.update({
  id: '/workout',
  path: '/workout',
  getParentRoute: () => AppRoute,
} as any)
const AppShellIndexRoute = AppShellIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppShellRoute,
} as any)
const AppShellExercisesRoute = AppShellExercisesRouteImport.update({
  id: '/exercises',
  path: '/exercises',
  getParentRoute: () => AppShellRoute,
} as any)
const AppShellHistoryRoute = AppShellHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AppShellRoute,
} as any)
const AppShellProgressRoute = AppShellProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => AppShellRoute,
} as any)
const AppShellRoutinesRoute = AppShellRoutinesRouteImport.update({
  id: '/routines',
  path: '/routines',
  getParentRoute: () => AppShellRoute,
} as any)
const AppShellSettingsRoute = AppShellSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppShellRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppShellIndexRoute
  '/login': typeof LoginRoute
  '/workout': typeof AppWorkoutRoute
  '/exercises': typeof AppShellExercisesRoute
  '/history': typeof AppShellHistoryRoute
  '/progress': typeof AppShellProgressRoute
  '/routines': typeof AppShellRoutinesRoute
  '/settings': typeof AppShellSettingsRoute
}
export interface FileRoutesByTo {
  '/': typeof AppShellIndexRoute
  '/login': typeof LoginRoute
  '/workout': typeof AppWorkoutRoute
  '/exercises': typeof AppShellExercisesRoute
  '/history': typeof AppShellHistoryRoute
  '/progress': typeof AppShellProgressRoute
  '/routines': typeof AppShellRoutinesRoute
  '/settings': typeof AppShellSettingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/_shell': typeof AppShellRouteWithChildren
  '/_app/workout': typeof AppWorkoutRoute
  '/_app/_shell/exercises': typeof AppShellExercisesRoute
  '/_app/_shell/history': typeof AppShellHistoryRoute
  '/_app/_shell/progress': typeof AppShellProgressRoute
  '/_app/_shell/routines': typeof AppShellRoutinesRoute
  '/_app/_shell/settings': typeof AppShellSettingsRoute
  '/_app/_shell/': typeof AppShellIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/workout'
    | '/exercises'
    | '/history'
    | '/progress'
    | '/routines'
    | '/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/workout'
    | '/exercises'
    | '/history'
    | '/progress'
    | '/routines'
    | '/settings'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/_app/_shell'
    | '/_app/workout'
    | '/_app/_shell/exercises'
    | '/_app/_shell/history'
    | '/_app/_shell/progress'
    | '/_app/_shell/routines'
    | '/_app/_shell/settings'
    | '/_app/_shell/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/_shell': {
      id: '/_app/_shell'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppShellRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/workout': {
      id: '/_app/workout'
      path: '/workout'
      fullPath: '/workout'
      preLoaderRoute: typeof AppWorkoutRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/_shell/': {
      id: '/_app/_shell/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppShellIndexRouteImport
      parentRoute: typeof AppShellRoute
    }
    '/_app/_shell/exercises': {
      id: '/_app/_shell/exercises'
      path: '/exercises'
      fullPath: '/exercises'
      preLoaderRoute: typeof AppShellExercisesRouteImport
      parentRoute: typeof AppShellRoute
    }
    '/_app/_shell/history': {
      id: '/_app/_shell/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof AppShellHistoryRouteImport
      parentRoute: typeof AppShellRoute
    }
    '/_app/_shell/progress': {
      id: '/_app/_shell/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof AppShellProgressRouteImport
      parentRoute: typeof AppShellRoute
    }
    '/_app/_shell/routines': {
      id: '/_app/_shell/routines'
      path: '/routines'
      fullPath: '/routines'
      preLoaderRoute: typeof AppShellRoutinesRouteImport
      parentRoute: typeof AppShellRoute
    }
    '/_app/_shell/settings': {
      id: '/_app/_shell/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppShellSettingsRouteImport
      parentRoute: typeof AppShellRoute
    }
  }
}

interface AppShellRouteChildren {
  AppShellExercisesRoute: typeof AppShellExercisesRoute
  AppShellHistoryRoute: typeof AppShellHistoryRoute
  AppShellProgressRoute: typeof AppShellProgressRoute
  AppShellRoutinesRoute: typeof AppShellRoutinesRoute
  AppShellSettingsRoute: typeof AppShellSettingsRoute
  AppShellIndexRoute: typeof AppShellIndexRoute
}

const AppShellRouteChildren: AppShellRouteChildren = {
  AppShellExercisesRoute: AppShellExercisesRoute,
  AppShellHistoryRoute: AppShellHistoryRoute,
  AppShellProgressRoute: AppShellProgressRoute,
  AppShellRoutinesRoute: AppShellRoutinesRoute,
  AppShellSettingsRoute: AppShellSettingsRoute,
  AppShellIndexRoute: AppShellIndexRoute,
}

const AppShellRouteWithChildren = AppShellRoute._addFileChildren(
  AppShellRouteChildren,
)

interface AppRouteChildren {
  AppShellRoute: typeof AppShellRouteWithChildren
  AppWorkoutRoute: typeof AppWorkoutRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppShellRoute: AppShellRouteWithChildren,
  AppWorkoutRoute: AppWorkoutRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
